# Generated by Django 5.0.6 on 2024-07-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_users_managers_remove_users_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_table',
        ),
    ]
