# Generated by Django 5.0.6 on 2024-08-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amounts',
            new_name='Amount',
        ),
        migrations.RenameModel(
            old_name='Consultations',
            new_name='Consultation',
        ),
        migrations.RenameModel(
            old_name='Designs',
            new_name='Design',
        ),
    ]
