# Generated by Django 5.0.6 on 2024-08-30 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(default=0, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='room_type',
        ),
        migrations.AddField(
            model_name='consultation',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.amount'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ConsultationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.amount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(limit_choices_to={'user_type_id__user_type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.payment_type')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.payment_type'),
        ),
    ]
