# Generated by Django 5.0.6 on 2025-03-12 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_roommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('position_z', models.FloatField(default=0)),
                ('rotation_y', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.roommodel')),
                ('virtual_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.virtualroom')),
            ],
            options={
                'unique_together': {('virtual_room', 'room_model')},
            },
        ),
        migrations.AddField(
            model_name='roommodel',
            name='virtual_rooms',
            field=models.ManyToManyField(through='home.VirtualRoomModel', to='home.virtualroom'),
        ),
        migrations.AddField(
            model_name='virtualroom',
            name='models',
            field=models.ManyToManyField(through='home.VirtualRoomModel', to='home.roommodel'),
        ),
    ]
