# Generated by Django 5.0.6 on 2025-03-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_position_fields'),
        ('home', '0003_virtualroommodel_roommodel_virtual_rooms_and_more'),
    ]

    operations = [
    ]
