# Generated by Django 5.0.6 on 2025-03-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20250313_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='position_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='position_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='rotation_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='scale',
            field=models.FloatField(default=1),
        ),
    ]
