# Generated by Django 5.0.6 on 2024-08-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
