# Generated by Django 5.0.6 on 2025-03-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_roommodel_position_x_roommodel_position_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='position_z',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='rotation_y',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='scale',
        ),
    ]
