# Generated by Django 5.0.6 on 2025-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_roommodel_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('bed', 'Bed'), ('window', 'Window'), ('door', 'Door'), ('decoration', 'Decoration')], default='furniture', max_length=100),
        ),
    ]
