# Generated by Django 5.0.6 on 2025-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_roommodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='category',
            field=models.CharField(choices=[('bed', 'Bed'), ('table', 'Table'), ('chair', 'Chair'), ('window', 'Window'), ('door', 'Door'), ('light', 'Light'), ('fan', 'Fan')], default='furniture', max_length=100),
        ),
    ]
