# Generated by Django 5.0.6 on 2025-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_roommodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='category',
            field=models.CharField(default='furniture', max_length=100),
        ),
    ]
