# Generated by Django 5.0.6 on 2025-03-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_roommodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualRoomFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('position_z', models.FloatField(default=0)),
                ('rotation_x', models.FloatField(default=0)),
                ('rotation_y', models.FloatField(default=0)),
                ('rotation_z', models.FloatField(default=0)),
                ('scale_x', models.FloatField(default=1)),
                ('scale_y', models.FloatField(default=1)),
                ('scale_z', models.FloatField(default=1)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.roommodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='home.virtualroom')),
            ],
        ),
    ]
