# Generated by Django 5.0.6 on 2025-03-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_virtualroomfurniture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='virtual_rooms',
        ),
        migrations.RemoveField(
            model_name='virtualroom',
            name='models',
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
