# Generated by Django 5.0.6 on 2025-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_roommodel_user_remove_roommodel_virtual_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='virtual_rooms',
            field=models.ManyToManyField(through='home.VirtualRoomModel', to='home.virtualroom'),
        ),
        migrations.AddField(
            model_name='virtualroom',
            name='models',
            field=models.ManyToManyField(through='home.VirtualRoomModel', to='home.roommodel'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='VirtualRoomFurniture',
        ),
    ]
