# Generated by Django 5.0.6 on 2025-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_roommodel_virtual_rooms_virtualroom_models_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualroommodel',
            old_name='scale',
            new_name='scale_x',
        ),
        migrations.AlterUniqueTogether(
            name='virtualroommodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='virtualroommodel',
            name='rotation_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='virtualroommodel',
            name='rotation_z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='virtualroommodel',
            name='scale_y',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='virtualroommodel',
            name='scale_z',
            field=models.FloatField(default=1),
        ),
    ]
