# Generated by Django 5.2 on 2025-05-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_scale_virtualroommodel_scale_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
