# Generated by Django 5.0.6 on 2024-10-01 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_order_delivery_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultationdate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consultationdate',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.design'),
        ),
        migrations.AlterUniqueTogether(
            name='consultationdate',
            unique_together={('designer', 'design', 'date_time')},
        ),
    ]
