# Generated by Django 5.0.6 on 2024-10-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_consultationdate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdate',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.design'),
        ),
    ]
