# Generated by Django 5.2 on 2025-05-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_order_delivery_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(default='Not Required', max_length=100),
        ),
    ]
