# Generated by Django 5.0.6 on 2024-10-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_consultationdate_design'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultationdate',
            unique_together={('designer', 'date_time')},
        ),
        migrations.RemoveField(
            model_name='consultationdate',
            name='design',
        ),
    ]
