# Generated by Django 5.2 on 2025-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_order_delivery_otp_order_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualroom',
            name='category',
            field=models.CharField(default='living_room', max_length=50),
        ),
    ]
