# Generated by Django 5.2 on 2025-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_virtualroom_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualroom',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
