# Generated by Django 5.2 on 2025-05-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_virtualroom_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualroom',
            name='category',
        ),
    ]
