# Generated by Django 5.0.6 on 2024-10-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_moodboard_updated_at_moodboard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodboarditem',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='moodboarditem',
            name='image',
        ),
        migrations.AddField(
            model_name='moodboarditem',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.design'),
        ),
        migrations.AddField(
            model_name='moodboarditem',
            name='item_type',
            field=models.CharField(choices=[('design', 'Design'), ('product', 'Product')], default='choice', max_length=10),
        ),
        migrations.AddField(
            model_name='moodboarditem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
