# Generated by Django 5.2 on 2025-05-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_virtualroom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualroom',
            name='category',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('dining_room', 'Dining Room'), ('office', 'Home Office'), ('other', 'Other')], default='living_room', max_length=50),
        ),
    ]
