# Generated by Django 5.0.6 on 2024-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_moodboarditem_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodboarditem',
            name='item_type',
            field=models.CharField(choices=[('design', 'Design'), ('product', 'Product')], max_length=10),
        ),
    ]
