# Generated by Django 5.0.6 on 2024-10-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_moodboarditem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('room_length', models.FloatField()),
                ('room_width', models.FloatField()),
                ('room_height', models.FloatField()),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='home.consultation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.design')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designed_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
