# Generated by Django 5.2 on 2025-05-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_virtualroom_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualroom',
            name='category',
        ),
    ]
