# Generated by Django 5.2 on 2025-05-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_virtualroom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualroom',
            name='room_category',
            field=models.CharField(default='Living Room', max_length=50),
        ),
    ]
