# Generated by Django 5.0.6 on 2024-10-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
