# Generated by Django 5.2 on 2025-05-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_virtualroom_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualroom',
            name='room_category',
        ),
    ]
