# Generated by Django 5.2 on 2025-05-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_virtualroom_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualroom',
            name='room_category',
            field=models.CharField(default='living room', max_length=50),
        ),
    ]
