# Generated by Django 5.2 on 2025-05-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_virtualroom_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualroom',
            name='door_height',
            field=models.FloatField(default=2.1),
        ),
        migrations.AddField(
            model_name='virtualroom',
            name='door_position',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='virtualroom',
            name='door_wall',
            field=models.CharField(default='front', max_length=20),
        ),
        migrations.AddField(
            model_name='virtualroom',
            name='door_width',
            field=models.FloatField(default=0.9),
        ),
    ]
