# Generated by Django 5.2 on 2025-05-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_virtualroom_door_height_virtualroom_door_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualroom',
            name='door_height',
        ),
        migrations.RemoveField(
            model_name='virtualroom',
            name='door_position',
        ),
        migrations.RemoveField(
            model_name='virtualroom',
            name='door_wall',
        ),
        migrations.RemoveField(
            model_name='virtualroom',
            name='door_width',
        ),
    ]
