# Generated by Django 5.0.6 on 2024-10-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_consultation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='feedback',
        ),
    ]
