# Generated by Django 5.0.6 on 2025-01-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_product_height_product_is_3d_enabled_product_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_3d_enabled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_3d',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.DeleteModel(
            name='RoomDesign',
        ),
    ]
