# Generated by Django 5.0.6 on 2025-02-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
